dt: 0.01


kps: [25, 25, 25, 0, 25, 25, 25, 0]
kds: [0.5, 0.5, 0.5, 0.3, 0.5, 0.5, 0.5, 0.3]



default_angles: [0, 1.2533, -2.0479, 0, 0, 1.2533, -2.0479, 0]
sit_angles: [0.093, 1.49, -3.14, 0, 0.093, 1.49, -3.14, 0]

lin_vel_scale: 1.0
ang_vel_scale: 0.25

cmd_init: [0.0, 0.0, 0.0]
# command_cfg

num_commands: 4
lin_vel_x_range: [-1.0, 1.0]
lin_vel_y_range: [0.0, 0.0]
ang_vel_range: [-3.14, 3.14]
height_target_range: [0.18, 0.32]

# env_cfg

num_actions: 8
